### ISSUE TITLE
No ESM support

### ISSUE THREAD

**Issue by lforst** [brustolin/timetac-automation#1]
Hi, this looks really awesome but it doesn't seem to have ESM support. Any ETA for ESM?

**Comment by lforst** [comment]
![image](https://github.com/brustolin/timetac-automation/assets/8118419/aa690df6-84fb-4b58-af04-276064e142fa)

**Comment by brustolin** [comment]
Sorry, we dont have plans for ESM.
Feel free to contribute 😁
